### ISSUE TITLE
Missing Docs

### ISSUE THREAD

**Issue by loschorts** [kcha0611/capstone#1]
Hey Ken,

I just started reviewing your Proposal. Your links for components, flux cycles, api endpoints, and schema are broken. Please fix these ASAP, I can't approve your project without them.

**Comment by kcha0611** [comment]
Hey Ken I fixed and pushed to git about an hour ago they should be working
now

**Comment by kcha0611** [comment]
Please let me know if you need anything else sorry about that I didn't know
how to create links onto my git until about an hour ago

**Comment by loschorts** [comment]
np thanks

**Comment by kcha0611** [comment]
Hey Ken do you think I would need a projectcontainer to hold all of the
projects that belong to a specific user or could i just make the direct
association with projects?
